site_name: Open NEC Project
docs_dir: Docs
site_description: The Open NEC Project is a massive, work-in-progress systems overhaul mod for Train Simulator 20xx that encompasses Amtrak's Northeast Corridor locale from Washington, DC to Boston.