FROM squidfunk/mkdocs-material
ADD https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/common-alpine.sh /tmp/library-scripts/
RUN ash /tmp/library-scripts/common-alpine.sh